---
- hosts: all 
  gather_facts: no
  tasks:
  - name: "Drush pmi on remote machine"
    raw: "drush pmi --format=json 2> /dev/null && echo ''"
    register: pmi_out

  - debug: msg="{{ pmi_out.stdout }}"
