---
- hosts: all 
  gather_facts: no
  tasks:
    - block:

      - name: "Download Drutiny"
        raw: "wget -O /tmp/drutiny_algm.phar https://github.com/bomoko/drutiny/raw/algm_release/releases/drutiny.phar"
        register: download_out

      - name: "Run Drutiny"
        raw: "LAGOON_DRUTINY_WEBHOOK_URL=https://hooks.lagoon.amazeeio.cloud LAGOON_DRUTINY_PROJECT_NAME={{ LAGOON_DRUTINY_PROJECT_NAME }} LAGOON_DRUTINY_ENVIRONMENT_NAME={{ LAGOON_DRUTINY_ENVIRONMENT_NAME }} php /tmp/drutiny_algm.phar --format=lagoon profile:run d8 @self"
        register: drutiny_out

      - name: "Remove Drutiny"
        raw: "rm /tmp/drutiny_algm.phar"
        register: status_out

      - name: "Debugging status"
        debug: msg="{{ status_out.stdout }}"


      rescue:
        - name: "Remove Drutiny"
          raw: "rm /tmp/drutiny_algm.phar"

        - name: "Debug output" 
          debug: msg="Could not complete Drutiny run for {{ inventory_hostname }}"
